export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const GET_CATS_PENDING = 'GET_CATS_PENDING';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILED = 'GET_CATS_FAILED';